// <auto-generated />
using System;
using CRM_KSK.Dal.PostgreSQL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CRM_KSK.Dal.PostgreSQL.Migrations
{
    [DbContext(typeof(CRM_KSKDbContext))]
    [Migration("20250120151837_InitialMagrations")]
    partial class InitialMagrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CRM_KSK.Core.Entities.Admin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("firstName");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lastName");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("passwordHash");

                    b.HasKey("Id")
                        .HasName("pK_admins");

                    b.ToTable("admins", (string)null);
                });

            modelBuilder.Entity("CRM_KSK.Core.Entities.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("dateOfBirth");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("firstName");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lastName");

                    b.Property<string>("ParentName")
                        .HasColumnType("text")
                        .HasColumnName("parentName");

                    b.Property<string>("ParentPhone")
                        .HasColumnType("text")
                        .HasColumnName("parentPhone");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<Guid?>("TrainerId")
                        .HasColumnType("uuid")
                        .HasColumnName("trainerId");

                    b.Property<int?>("TrainingId")
                        .HasColumnType("integer")
                        .HasColumnName("trainingId");

                    b.HasKey("Id")
                        .HasName("pK_clients");

                    b.HasIndex("TrainerId")
                        .HasDatabaseName("iX_clients_trainerId");

                    b.HasIndex("TrainingId")
                        .HasDatabaseName("iX_clients_trainingId");

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("CRM_KSK.Core.Entities.Schedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("clientId");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("clientName");

                    b.Property<string>("Day")
                        .HasColumnType("text")
                        .HasColumnName("day");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time");

                    b.Property<Guid?>("TrainerId")
                        .HasColumnType("uuid")
                        .HasColumnName("trainerId");

                    b.Property<string>("TrainerName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("trainerName");

                    b.Property<string>("TrainingType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("trainingType");

                    b.HasKey("Id")
                        .HasName("pK_schedules");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("iX_schedules_clientId");

                    b.HasIndex("TrainerId")
                        .HasDatabaseName("iX_schedules_trainerId");

                    b.ToTable("schedules", (string)null);
                });

            modelBuilder.Entity("CRM_KSK.Core.Entities.Trainer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("dateOfBirth");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("firstName");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lastName");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("Specialization")
                        .HasColumnType("text")
                        .HasColumnName("specialization");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("surname");

                    b.HasKey("Id")
                        .HasName("pK_trainers");

                    b.ToTable("trainers", (string)null);
                });

            modelBuilder.Entity("CRM_KSK.Core.Entities.Training", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<Guid>("TrainerId")
                        .HasColumnType("uuid")
                        .HasColumnName("trainerId");

                    b.HasKey("Id")
                        .HasName("pK_trainings");

                    b.HasIndex("TrainerId")
                        .HasDatabaseName("iX_trainings_trainerId");

                    b.ToTable("trainings", (string)null);
                });

            modelBuilder.Entity("CRM_KSK.Core.Entities.Client", b =>
                {
                    b.HasOne("CRM_KSK.Core.Entities.Trainer", "Trainer")
                        .WithMany("Clients")
                        .HasForeignKey("TrainerId")
                        .HasConstraintName("fK_clients_trainers_trainerId");

                    b.HasOne("CRM_KSK.Core.Entities.Training", null)
                        .WithMany("Clients")
                        .HasForeignKey("TrainingId")
                        .HasConstraintName("fK_clients_trainings_trainingId");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("CRM_KSK.Core.Entities.Schedule", b =>
                {
                    b.HasOne("CRM_KSK.Core.Entities.Client", null)
                        .WithMany("Schedules")
                        .HasForeignKey("ClientId")
                        .HasConstraintName("fK_schedules_clients_clientId");

                    b.HasOne("CRM_KSK.Core.Entities.Trainer", null)
                        .WithMany("Schedules")
                        .HasForeignKey("TrainerId")
                        .HasConstraintName("fK_schedules_trainers_trainerId");
                });

            modelBuilder.Entity("CRM_KSK.Core.Entities.Training", b =>
                {
                    b.HasOne("CRM_KSK.Core.Entities.Trainer", "Trainer")
                        .WithMany()
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fK_trainings_trainers_trainerId");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("CRM_KSK.Core.Entities.Client", b =>
                {
                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("CRM_KSK.Core.Entities.Trainer", b =>
                {
                    b.Navigation("Clients");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("CRM_KSK.Core.Entities.Training", b =>
                {
                    b.Navigation("Clients");
                });
#pragma warning restore 612, 618
        }
    }
}
