// <auto-generated />
using System;
using CRM_KSK.Dal.PostgreSQL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CRM_KSK.Dal.PostgreSQL.Migrations
{
    [DbContext(typeof(CRM_KSKDbContext))]
    [Migration("20250806114432_FixErrorDeletedTraining")]
    partial class FixErrorDeletedTraining
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CRM_KSK.Core.Entities.Admin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("firstName");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lastName");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("passwordHash");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pK_admins");

                    b.ToTable("admins", (string)null);
                });

            modelBuilder.Entity("CRM_KSK.Core.Entities.BirthdayNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("Birthday")
                        .HasColumnType("date")
                        .HasColumnName("birthday");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("personId");

                    b.Property<string>("PersonType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("personType");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.HasKey("Id")
                        .HasName("pK_birthDays");

                    b.ToTable("birthDays", (string)null);
                });

            modelBuilder.Entity("CRM_KSK.Core.Entities.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("dateOfBirth");

                    b.Property<DateTime>("DateRegister")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dateRegister");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("firstName");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isDeleted");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lastName");

                    b.Property<string>("ParentName")
                        .HasColumnType("text")
                        .HasColumnName("parentName");

                    b.Property<string>("ParentPhone")
                        .HasColumnType("text")
                        .HasColumnName("parentPhone");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.HasKey("Id")
                        .HasName("pK_clients");

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("CRM_KSK.Core.Entities.Membership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AmountTraining")
                        .HasColumnType("integer")
                        .HasColumnName("amountTraining");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("clientId");

                    b.Property<DateOnly>("DateEnd")
                        .HasColumnType("date")
                        .HasColumnName("dateEnd");

                    b.Property<DateOnly>("DateStart")
                        .HasColumnType("date")
                        .HasColumnName("dateStart");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isDeleted");

                    b.Property<bool>("IsOneTimeTraining")
                        .HasColumnType("boolean")
                        .HasColumnName("isOneTimeTraining");

                    b.Property<string>("StatusMembership")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("statusMembership");

                    b.Property<int>("TypeTrainings")
                        .HasColumnType("integer")
                        .HasColumnName("typeTrainings");

                    b.HasKey("Id")
                        .HasName("pK_memberships");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("iX_memberships_clientId");

                    b.ToTable("memberships", (string)null);
                });

            modelBuilder.Entity("CRM_KSK.Core.Entities.MembershipDeductionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("clientId");

                    b.Property<DateOnly>("DeductionDate")
                        .HasColumnType("date")
                        .HasColumnName("deductionDate");

                    b.Property<bool>("MembershipExpired")
                        .HasColumnType("boolean")
                        .HasColumnName("membershipExpired");

                    b.Property<Guid?>("MembershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("membershipId");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uuid")
                        .HasColumnName("scheduleId");

                    b.Property<Guid>("TrainingId")
                        .HasColumnType("uuid")
                        .HasColumnName("trainingId");

                    b.Property<int>("TrainingType")
                        .HasColumnType("integer")
                        .HasColumnName("trainingType");

                    b.Property<int>("TrainingsAfterDeduction")
                        .HasColumnType("integer")
                        .HasColumnName("trainingsAfterDeduction");

                    b.Property<int>("TrainingsBeforeDeduction")
                        .HasColumnType("integer")
                        .HasColumnName("trainingsBeforeDeduction");

                    b.HasKey("Id")
                        .HasName("pK_membershipDeductionLogs");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("iX_membershipDeductionLogs_clientId");

                    b.HasIndex("DeductionDate")
                        .HasDatabaseName("iX_membershipDeductionLogs_deductionDate");

                    b.HasIndex("MembershipExpired")
                        .HasDatabaseName("iX_membershipDeductionLogs_membershipExpired");

                    b.HasIndex("MembershipId")
                        .HasDatabaseName("iX_membershipDeductionLogs_membershipId");

                    b.HasIndex("ScheduleId")
                        .HasDatabaseName("iX_membershipDeductionLogs_scheduleId");

                    b.HasIndex("TrainingId")
                        .HasDatabaseName("iX_membershipDeductionLogs_trainingId");

                    b.HasIndex("TrainingType")
                        .HasDatabaseName("iX_membershipDeductionLogs_trainingType");

                    b.ToTable("membershipDeductionLogs", (string)null);
                });

            modelBuilder.Entity("CRM_KSK.Core.Entities.Schedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("interval")
                        .HasColumnName("time");

                    b.HasKey("Id")
                        .HasName("pK_schedules");

                    b.ToTable("schedules", (string)null);
                });

            modelBuilder.Entity("CRM_KSK.Core.Entities.ScheduleComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("commentText");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("interval")
                        .HasColumnName("time");

                    b.HasKey("Id")
                        .HasName("pK_scheduleComments");

                    b.ToTable("scheduleComments", (string)null);
                });

            modelBuilder.Entity("CRM_KSK.Core.Entities.Trainer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("dateOfBirth");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("firstName");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isDeleted");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lastName");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("passwordHash");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("surname");

                    b.HasKey("Id")
                        .HasName("pK_trainers");

                    b.ToTable("trainers", (string)null);
                });

            modelBuilder.Entity("CRM_KSK.Core.Entities.Training", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uuid")
                        .HasColumnName("scheduleId");

                    b.Property<Guid>("TrainerId")
                        .HasColumnType("uuid")
                        .HasColumnName("trainerId");

                    b.Property<int>("TypeTrainings")
                        .HasColumnType("integer")
                        .HasColumnName("typeTrainings");

                    b.HasKey("Id")
                        .HasName("pK_trainings");

                    b.HasIndex("ScheduleId")
                        .HasDatabaseName("iX_trainings_scheduleId");

                    b.HasIndex("TrainerId")
                        .HasDatabaseName("iX_trainings_trainerId");

                    b.ToTable("trainings", (string)null);
                });

            modelBuilder.Entity("CRM_KSK.Core.Entities.WorkHorse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contentText");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("HorseName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("horseName");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isDeleted");

                    b.Property<int>("RowNumber")
                        .HasColumnType("integer")
                        .HasColumnName("rowNumber");

                    b.HasKey("Id")
                        .HasName("pK_workHorses");

                    b.ToTable("workHorses", (string)null);
                });

            modelBuilder.Entity("ClientTraining", b =>
                {
                    b.Property<Guid>("ClientsId")
                        .HasColumnType("uuid")
                        .HasColumnName("clientsId");

                    b.Property<Guid>("TrainingsId")
                        .HasColumnType("uuid")
                        .HasColumnName("trainingsId");

                    b.HasKey("ClientsId", "TrainingsId")
                        .HasName("pK_clientTraining");

                    b.HasIndex("TrainingsId")
                        .HasDatabaseName("iX_clientTraining_trainingsId");

                    b.ToTable("clientTraining", (string)null);
                });

            modelBuilder.Entity("CRM_KSK.Core.Entities.Membership", b =>
                {
                    b.HasOne("CRM_KSK.Core.Entities.Client", "Client")
                        .WithMany("Memberships")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fK_memberships_clients_clientId");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("CRM_KSK.Core.Entities.MembershipDeductionLog", b =>
                {
                    b.HasOne("CRM_KSK.Core.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fK_membershipDeductionLogs_clients_clientId");

                    b.HasOne("CRM_KSK.Core.Entities.Membership", "Membership")
                        .WithMany()
                        .HasForeignKey("MembershipId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fK_membershipDeductionLogs_memberships_membershipId");

                    b.HasOne("CRM_KSK.Core.Entities.Schedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fK_membershipDeductionLogs_schedules_scheduleId");

                    b.HasOne("CRM_KSK.Core.Entities.Training", "Training")
                        .WithMany()
                        .HasForeignKey("TrainingId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired()
                        .HasConstraintName("fK_membershipDeductionLogs_trainings_trainingId");

                    b.Navigation("Client");

                    b.Navigation("Membership");

                    b.Navigation("Schedule");

                    b.Navigation("Training");
                });

            modelBuilder.Entity("CRM_KSK.Core.Entities.Training", b =>
                {
                    b.HasOne("CRM_KSK.Core.Entities.Schedule", "Schedule")
                        .WithMany("Trainings")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fK_trainings_schedules_scheduleId");

                    b.HasOne("CRM_KSK.Core.Entities.Trainer", "Trainer")
                        .WithMany("Trainings")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fK_trainings_trainers_trainerId");

                    b.Navigation("Schedule");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("ClientTraining", b =>
                {
                    b.HasOne("CRM_KSK.Core.Entities.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fK_clientTraining_clients_clientsId");

                    b.HasOne("CRM_KSK.Core.Entities.Training", null)
                        .WithMany()
                        .HasForeignKey("TrainingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fK_clientTraining_trainings_trainingsId");
                });

            modelBuilder.Entity("CRM_KSK.Core.Entities.Client", b =>
                {
                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("CRM_KSK.Core.Entities.Schedule", b =>
                {
                    b.Navigation("Trainings");
                });

            modelBuilder.Entity("CRM_KSK.Core.Entities.Trainer", b =>
                {
                    b.Navigation("Trainings");
                });
#pragma warning restore 612, 618
        }
    }
}
