// <auto-generated />
using System;
using CRM_KSK.Dal.PostgreSQL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CRM_KSK.Dal.PostgreSQL.Migrations
{
    [DbContext(typeof(CRM_KSKDbContext))]
    [Migration("20250220130448_updateStructureTable")]
    partial class updateStructureTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CRM_KSK.Core.Entities.Admin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("firstName");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lastName");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("passwordHash");

                    b.HasKey("Id")
                        .HasName("pK_admins");

                    b.ToTable("admins", (string)null);
                });

            modelBuilder.Entity("CRM_KSK.Core.Entities.BirthdayNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("Birthday")
                        .HasColumnType("date")
                        .HasColumnName("birthday");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("personId");

                    b.Property<string>("PersonType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("personType");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.HasKey("Id")
                        .HasName("pK_birthDays");

                    b.ToTable("birthDays", (string)null);
                });

            modelBuilder.Entity("CRM_KSK.Core.Entities.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("dateOfBirth");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("firstName");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lastName");

                    b.Property<string>("ParentName")
                        .HasColumnType("text")
                        .HasColumnName("parentName");

                    b.Property<string>("ParentPhone")
                        .HasColumnType("text")
                        .HasColumnName("parentPhone");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.HasKey("Id")
                        .HasName("pK_clients");

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("CRM_KSK.Core.Entities.Membership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AmountTraining")
                        .HasColumnType("integer")
                        .HasColumnName("amountTraining");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("clientId");

                    b.Property<DateOnly>("DateEnd")
                        .HasColumnType("date")
                        .HasColumnName("dateEnd");

                    b.Property<DateOnly>("DateStart")
                        .HasColumnType("date")
                        .HasColumnName("dateStart");

                    b.Property<string>("StatusMembership")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("statusMembership");

                    b.Property<int>("TypeTrainings")
                        .HasColumnType("integer")
                        .HasColumnName("typeTrainings");

                    b.HasKey("Id")
                        .HasName("pK_memberships");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("iX_memberships_clientId");

                    b.ToTable("memberships", (string)null);
                });

            modelBuilder.Entity("CRM_KSK.Core.Entities.Schedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("interval")
                        .HasColumnName("time");

                    b.HasKey("Id")
                        .HasName("pK_schedules");

                    b.ToTable("schedules", (string)null);
                });

            modelBuilder.Entity("CRM_KSK.Core.Entities.Trainer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("dateOfBirth");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("firstName");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lastName");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("surname");

                    b.HasKey("Id")
                        .HasName("pK_trainers");

                    b.ToTable("trainers", (string)null);
                });

            modelBuilder.Entity("CRM_KSK.Core.Entities.Training", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uuid")
                        .HasColumnName("scheduleId");

                    b.Property<Guid>("TrainerId")
                        .HasColumnType("uuid")
                        .HasColumnName("trainerId");

                    b.Property<int>("TypeTrainings")
                        .HasColumnType("integer")
                        .HasColumnName("typeTrainings");

                    b.HasKey("Id")
                        .HasName("pK_trainings");

                    b.HasIndex("ScheduleId")
                        .HasDatabaseName("iX_trainings_scheduleId");

                    b.HasIndex("TrainerId")
                        .HasDatabaseName("iX_trainings_trainerId");

                    b.ToTable("trainings", (string)null);
                });

            modelBuilder.Entity("ClientTraining", b =>
                {
                    b.Property<Guid>("ClientsId")
                        .HasColumnType("uuid")
                        .HasColumnName("clientsId");

                    b.Property<Guid>("TrainingsId")
                        .HasColumnType("uuid")
                        .HasColumnName("trainingsId");

                    b.HasKey("ClientsId", "TrainingsId")
                        .HasName("pK_clientTraining");

                    b.HasIndex("TrainingsId")
                        .HasDatabaseName("iX_clientTraining_trainingsId");

                    b.ToTable("clientTraining", (string)null);
                });

            modelBuilder.Entity("CRM_KSK.Core.Entities.Membership", b =>
                {
                    b.HasOne("CRM_KSK.Core.Entities.Client", "Client")
                        .WithMany("Membership")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fK_memberships_clients_clientId");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("CRM_KSK.Core.Entities.Training", b =>
                {
                    b.HasOne("CRM_KSK.Core.Entities.Schedule", "Schedule")
                        .WithMany("Trainings")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fK_trainings_schedules_scheduleId");

                    b.HasOne("CRM_KSK.Core.Entities.Trainer", "Trainer")
                        .WithMany("Trainings")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fK_trainings_trainers_trainerId");

                    b.Navigation("Schedule");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("ClientTraining", b =>
                {
                    b.HasOne("CRM_KSK.Core.Entities.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fK_clientTraining_clients_clientsId");

                    b.HasOne("CRM_KSK.Core.Entities.Training", null)
                        .WithMany()
                        .HasForeignKey("TrainingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fK_clientTraining_trainings_trainingsId");
                });

            modelBuilder.Entity("CRM_KSK.Core.Entities.Client", b =>
                {
                    b.Navigation("Membership");
                });

            modelBuilder.Entity("CRM_KSK.Core.Entities.Schedule", b =>
                {
                    b.Navigation("Trainings");
                });

            modelBuilder.Entity("CRM_KSK.Core.Entities.Trainer", b =>
                {
                    b.Navigation("Trainings");
                });
#pragma warning restore 612, 618
        }
    }
}
